# Generated by Django 2.2.17 on 2022-02-13 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('githubs', '0010_githubuser_total_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubuser',
            name='previous_user_rank',
            field=models.IntegerField(default=None, null=True, verbose_name='이전 랭킹'),
        ),
        migrations.AlterField(
            model_name='githubuser',
            name='avatar_url',
            field=models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='깃헙 프로필 URL'),
        ),
        migrations.AlterField(
            model_name='githubuser',
            name='bio',
            field=models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='설명'),
        ),
        migrations.AlterField(
            model_name='githubuser',
            name='blog',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='블로그 주소'),
        ),
        migrations.AlterField(
            model_name='githubuser',
            name='company',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='회사'),
        ),
        migrations.AlterField(
            model_name='githubuser',
            name='continuous_commit_day',
            field=models.IntegerField(default=0, verbose_name='1일 1커밋 지속 날짜 카운트'),
        ),
        migrations.AlterField(
            model_name='githubuser',
            name='email',
            field=models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='이메일'),
        ),
        migrations.AlterField(
            model_name='githubuser',
            name='followers',
            field=models.IntegerField(blank=True, default=0, verbose_name='팔로워'),
        ),
        migrations.AlterField(
            model_name='githubuser',
            name='following',
            field=models.IntegerField(blank=True, default=0, verbose_name='팔로잉'),
        ),
        migrations.AlterField(
            model_name='githubuser',
            name='location',
            field=models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='국가정보(country)'),
        ),
        migrations.AlterField(
            model_name='githubuser',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='유저이름'),
        ),
        migrations.AlterField(
            model_name='githubuser',
            name='public_repos',
            field=models.IntegerField(blank=True, default=0, verbose_name='공식 레포수'),
        ),
        migrations.AlterField(
            model_name='githubuser',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'none'), (5, 'completed'), (10, 'waiting'), (15, 'updating'), (20, 'fail')], default=0, verbose_name='업데이트 상태'),
        ),
        migrations.AlterField(
            model_name='githubuser',
            name='tier',
            field=models.SmallIntegerField(choices=[(35, 'Challenger'), (30, 'Master'), (25, 'Diamond'), (20, 'Platinum'), (15, 'Gold'), (10, 'Silver'), (5, 'Bronze'), (0, 'UnRank')], default=0, verbose_name='티어'),
        ),
        migrations.AlterField(
            model_name='githubuser',
            name='total_contribution',
            field=models.IntegerField(default=0, verbose_name='총 컨트리뷰션'),
        ),
        migrations.AlterField(
            model_name='githubuser',
            name='total_score',
            field=models.IntegerField(blank=True, default=0, verbose_name='종합점수'),
        ),
        migrations.AlterField(
            model_name='githubuser',
            name='total_stargazers_count',
            field=models.IntegerField(default=0, verbose_name='총 스타(star)수'),
        ),
        migrations.AlterField(
            model_name='githubuser',
            name='user_rank',
            field=models.IntegerField(default=None, null=True, verbose_name='현재 랭킹'),
        ),
        migrations.AlterField(
            model_name='githubuser',
            name='username',
            field=models.CharField(max_length=200, unique=True, verbose_name='Github ID'),
        ),
        migrations.AlterField(
            model_name='repository',
            name='languages',
            field=models.CharField(default='', help_text='레포지토리에서 사용하는 모든 언어(json)', max_length=1000),
        ),
        migrations.AlterField(
            model_name='repository',
            name='rep_language',
            field=models.CharField(default='', help_text='대표언어', max_length=100),
        ),
        migrations.AlterField(
            model_name='userlanguage',
            name='number',
            field=models.IntegerField(default=0, help_text='number of bytes of code written in that language.'),
        ),
    ]
