# Generated by Django 2.2.17 on 2022-05-07 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('githubs', '0011_auto_20220213_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('username', models.CharField(max_length=200, unique=True, verbose_name='Github ID')),
            ],
            options={
                'abstract': False,
                'default_manager_name': 'objects',
            },
        ),
        migrations.AlterField(
            model_name='githubuser',
            name='tier',
            field=models.SmallIntegerField(choices=[(35, 'Challenger'), (33, 'GrandMaster'), (30, 'Master'), (25, 'Diamond'), (20, 'Platinum'), (15, 'Gold'), (10, 'Silver'), (5, 'Bronze'), (0, 'Iron')], default=0, verbose_name='티어'),
        ),
    ]
