# Generated by Django 2.2.17 on 2023-08-10 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('githubs', '0012_auto_20220507_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='full_name',
            field=models.CharField(max_length=500),
        ),
    ]
