# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mariadb:
        image: mysql:latest
        env:
          MYSQL_USER: ci_user
          MYSQL_PASSWORD: ci_user_pw123
          MYSQL_DATABASE: opgc_ci_db
          MYSQL_ROOT_PASSWORD: ci_user_pw123
        ports:
          - 3306:3306 
        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3
        
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/base.txt
        
    - name: Start Pytest
      run: |
        cd opgc
        pytest
        
    - name: Slack Notification
      uses: homoluctus/slatify@master
      if: always()
      with:
        type: ${{ job.status }}
        username: 'CI 테스트 봇'
        job_name: '테스트 케이스 검증'
        mention: 'here'
        mention_if: 'failure'
        channel: '#logs'
        url: ${{ secrets.SLACK_WEBHOOK }}
